### ISSUE TITLE
Cannot read property 'length' of undefined - not catched?

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/mp3-downloader#21]
When trying to download the following song
```$ mp3 "the lighthouse hollywood"```
I get the following
```> Cannot read property 'length' of undefined```

**Comment by JochenBe** [comment]
Same here! 😉

```
$ mp3 beau collins
✖ Cannot read property 'length' of undefined
```

**Comment by JochenBe** [comment]
Error occurs at line 120 in services.js.
It must be a bug in youtube-dl-status, please fix your library @Jense5 ! 😇

**Comment by Jense5** [comment]
Weird, is this really a bug in `youtube-dl`? I'll fix this after dinner! 👌

**Comment by Jense5** [comment]
I think I fixed this, but haven't released yet.  
You can already try it from the `development` branch but I'll release later tonight.
