### ISSUE TITLE
Downloading particular song is faster than any other, but does not download anything

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/mp3-downloader#22]
When downloading the following:
```mp3 "kygo it aint me"```
It outputs:
```> Download complete in 4.23s! ```
However, no song is downloaded. 
4.23s is also "too fast" compared to other songs (ca. 10s)

**Comment by Jense5** [comment]
Can't explain why, but looks like it works on `development` branch after the major refactor.  
Feel free to reopen if this issue reoccurs.
