### ISSUE TITLE
Checking on audio length returns incorrect results

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/mp3-downloader#23]
By checking on length of song, incorrect results might be returned. For example:
```$ mp3 "kraantje pappie pompen"```
A remix of the song gets downloaded.
<img width="427" alt="screen shot 2017-04-25 at 17 25 18" src="https://cloud.githubusercontent.com/assets/7559898/25393605/33bd0552-29dc-11e7-88f1-b25dca9dec96.png">

**Comment by Jense5** [comment]
@JochenBe

Duration should not be a tag, right? I thought it should've been calculated based on the track?

**Comment by Jense5** [comment]
Is this always the case? I am not having this issue so I assume it is fixed since the major refactor?  
Reopen if this reoccurs. 🙃
