### ISSUE TITLE
Add option --force (or similar) to specify youtube video

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/mp3-downloader#25]
For example, one could be able to do:
```$ mp3 "ajr weak" --force https://www.youtube.com/watch?v=1eHK4sH2-O4```
In the example above, without ```--force```, a radio-session version of the song is downloaded (which is not the original). When specifying with force, one could choose which song to download (if an incorrect version is downloaded), but still use the metadata from iTunes to tag the song. I presume the specified url is one second longer than the length tag provided by iTunes and thus not selected.

**Comment by Jense5** [comment]
Added in `development` branch.
