### ISSUE TITLE
Option to manually pass country

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/mp3-downloader#26]
No results are found when trying this query (don't question the song ;) ):
```https://itunes.apple.com/search?term="a touch of class my heart beats like a drum"&country=BE```
However, this query returns the correct song (it's a German band)
```https://itunes.apple.com/search?term="a touch of class my heart beats like a drum"&country=DE```

Perhaps include a tag like ```--country``` to manually specify the country of the iTunes store to search?

**Comment by Jense5** [comment]
Thanks for pull request #27!
